/** Package name (runtime export for tooling / coverage). */
export const RS_TENSOR_MCP_PACKAGE = "rs-tensor-mcp";

export {
  RsTensorClient,
  RsTensorMcpError,
  defaultMcpStdioParams,
  defaultRsTensorRoot,
  extractTextContent,
  trainXorMlp,
  type RsTensorClientOptions,
  type RsTensorToolCaller,
  type TrainXorOptions,
} from "./client.js";
export type {
  AttentionForwardArgs,
  AutogradExprArgs,
  AutogradNeuronArgs,
  AutogradNeuronTensorArgs,
  AvgPool2dArgs,
  BatchNorm2dArgs,
  CargoExecArgs,
  CnnForwardArgs,
  CnnForwardResult,
  CnnLayerSpec,
  Conv2dArgs,
  CreateDatasetArgs,
  CreateDatasetResult,
  EvaluateMlpArgs,
  FeatureMapInfo,
  FlattenArgs,
  GgufInspectArgs,
  GgufLoadTensorArgs,
  GlobalAvgPoolArgs,
  InitCnnArgs,
  InitCnnResult,
  InitMlpArgs,
  InitMlpResult,
  JsonObject,
  LayerDef,
  LlamaGenerateArgs,
  LlamaLoadArgs,
  MaxPool2dArgs,
  MlpForwardArgs,
  MlpPredictArgs,
  MseLossArgs,
  ReadFileArgs,
  TensorBinaryOpArgs,
  TensorCreateArgs,
  TensorGet2dArgs,
  TensorGetArgs,
  TensorInspectArgs,
  TensorMatmulArgs,
  TensorOpResult,
  TensorReshapeArgs,
  TensorTransposeArgs,
  TrainMlpArgs,
  TrainMlpResult,
} from "./types.js";
